# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Modifications Copyright 2019 Sipher Inc.

version: '2'

services:

  orderer.sipher.co:
    container_name: orderer.sipher.co
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_HOST=1-ordsipher
      - ORG=ordsipher
      - FABRIC_CA_CLIENT_HOME=/etc/hyperledger/orderer
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        # - ../data/orgs/ordsipher/msp:/var/hyperledger/orderer/msp
        # - ../crypto-config/ordererOrganizations/sipher.co/orderers/orderer.sipher.co/tls/:/var/hyperledger/orderer/tls
        - orderer.sipher.co:/var/hyperledger/production/orderer
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/scripts
        - ../data/:/data
    ports:
      - 7050:7050

  peer0.libertas.sipher.co:
    container_name: peer0.libertas.sipher.co
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - PEER_HOST=1-sipher
      - ORG=sipher
      - FABRIC_CA_CLIENT_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/msp
      - CORE_PEER_ID=peer0.libertas.sipher.co
      - CORE_PEER_ADDRESS=peer0.libertas.sipher.co:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.libertas.sipher.co:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.libertas.sipher.co:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.libertas.sipher.co:7051
      - CORE_PEER_LOCALMSPID=SipherMSP
    volumes:
        - /var/run/:/host/var/run/
        # - ../data/orgs/sipher/msp:/etc/hyperledger/fabric/msp
        # - ../crypto-config/peerOrganizations/libertas.sipher.co/peers/peer0.libertas.sipher.co/tls:/etc/hyperledger/fabric/tls
        - peer0.libertas.sipher.co:/var/hyperledger/production
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
        - ../data/:/data
    ports:
      - 7051:7051

  peer1.libertas.sipher.co:
    container_name: peer1.libertas.sipher.co
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - PEER_HOST=2-sipher
      - ORG=sipher
      - FABRIC_CA_CLIENT_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/msp
      - CORE_PEER_ID=peer1.libertas.sipher.co
      - CORE_PEER_ADDRESS=peer1.libertas.sipher.co:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.libertas.sipher.co:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.libertas.sipher.co:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.libertas.sipher.co:7051
      - CORE_PEER_LOCALMSPID=SipherMSP
    volumes:
        - /var/run/:/host/var/run/
        # - ../data/orgs/sipher/msp:/etc/hyperledger/fabric/msp
        # - ../crypto-config/peerOrganizations/libertas.sipher.co/peers/peer1.libertas.sipher.co/tls:/etc/hyperledger/fabric/tls
        - peer1.libertas.sipher.co:/var/hyperledger/production
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
        - ../data/:/data
    ports:
      - 8051:8051

  peer0.libertas.whiteboxplatform.com:
    container_name: peer0.libertas.whiteboxplatform.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - PEER_HOST=1-whiteboxplatform
      - ORG=whiteboxplatform
      - FABRIC_CA_CLIENT_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/msp
      - CORE_PEER_ID=peer0.libertas.whiteboxplatform.com
      - CORE_PEER_ADDRESS=peer0.libertas.whiteboxplatform.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.libertas.whiteboxplatform.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.libertas.whiteboxplatform.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.libertas.whiteboxplatform.com:10051
      - CORE_PEER_LOCALMSPID=WhiteBoxPlatformMSP
    volumes:
        - /var/run/:/host/var/run/
        # - ../data/orgs/whiteboxplatform/msp:/etc/hyperledger/fabric/msp
        # - ../crypto-config/peerOrganizations/libertas.whiteboxplatform.com/peers/peer0.libertas.whiteboxplatform.com/tls:/etc/hyperledger/fabric/tls
        - peer0.libertas.whiteboxplatform.com:/var/hyperledger/production
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
        - ../data/:/data
    ports:
      - 9051:9051

  peer1.libertas.whiteboxplatform.com:
    container_name: peer1.libertas.whiteboxplatform.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - PEER_HOST=2-whiteboxplatform
      - ORG=whiteboxplatform
      - FABRIC_CA_CLIENT_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer  
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/msp
      - CORE_PEER_ID=peer1.libertas.whiteboxplatform.com
      - CORE_PEER_ADDRESS=peer1.libertas.whiteboxplatform.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.libertas.whiteboxplatform.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.libertas.whiteboxplatform.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.libertas.whiteboxplatform.com:9051
      - CORE_PEER_LOCALMSPID=WhiteBoxPlatformMSP
    volumes:
        - /var/run/:/host/var/run/
        # - ../data/orgs/whiteboxplatform/msp:/etc/hyperledger/fabric/msp # the org msp?
        # - ../crypto-config/peerOrganizations/libertas.whiteboxplatform.com/peers/peer1.libertas.whiteboxplatform.com/tls:/etc/hyperledger/fabric/tls
        - peer1.libertas.whiteboxplatform.com:/var/hyperledger/production
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
        - ../data/:/data
    ports:
      - 10051:10051
