# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Modifications Copyright 2019 Sipher Inc.

version: '2'

networks:
  dev_network:

services:
  ca0:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-sipher
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_PORT=7054

      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.libertas.sipher.co-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${DEV_NETWORK_CA1_PRIVATE_KEY}

      # - ORG=sipher
      # - DEV_NETWORK_CA_PRIVATE_KEY=${DEV_NETWORK_CA1_PRIVATE_KEY}
    ports:
      - "7054:7054"
    command: sh -c './scripts/start-ca.sh'
    volumes:
      # - ./crypto-config/peerOrganizations/libertas.sipher.co/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./data:/data
      - ./scripts:/scripts
    container_name: ca-sipher
    networks:
      - dev_network
  

  ca1:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-whiteboxplatform
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_PORT=8054

      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.libertas.whiteboxplatform.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${DEV_NETWORK_CA2_PRIVATE_KEY}

      # - ORG=whiteboxplatform
      # - DEV_NETWORK_CA_PRIVATE_KEY=${DEV_NETWORK_CA2_PRIVATE_KEY}
    ports:
      - "8054:8054"
    command: sh -c './scripts/start-ca.sh'
    volumes:
      # - ./crypto-config/peerOrganizations/libertas.whiteboxplatform.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./data:/data
      - ./scripts:/scripts
    container_name: ca-whitebox
    networks:
      - dev_network