NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.libertas.whiteboxplatform.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.libertas.whiteboxplatform.com-cert.pem
    OrganizationalUnitIdentifier: peer
