NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.libertas.sipher.co-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.libertas.sipher.co-cert.pem
    OrganizationalUnitIdentifier: peer
